#!/bin/bash

ACCOUNT="ict26_esp_0"
PARTITION="boost_usr_prod"
QOS=""
MAIL="wtang@ictp.it"
TIME="04:00:00"
MEM="60G"
JOB_NAME="att-rddpm-rwp-2098"
N_GPU="1"

SOURCE_PATH="/leonardo/home/userexternal/$USER/Conda_init.txt"
ENV_PATH="/leonardo/pub/userexternal/sdigioia/sdigioia/env/RLenv"
MAIN_PATH="$HOME/benchmarks/Experiments_GNN_diffusion_ddpm_recon_wet_loss"
VALENTINA_PATH="$HOME/benchmarks/Experiments_Valentina"

GNN_PRED_FILE="/leonardo_work/ICT26_ESP_0/wtang/CORDEXML-BENCHMARK/train/SA_domain/Emulator_hist_future/predictions/attention/attention_pr_SA_Emulator_CosAnnLR_ALPHA01_BETA005_LR0008_bin25_1650_e200_train1961_1980_2080_2099/G_SA_attention_pr_train_1961_1980_2080_2099.pkl"
GRAPH_FILE="/leonardo_work/ICT26_ESP_0/wtang/CORDEXML-GRAPHS/SA_domain_attention/Emulator_hist_future/pr/train/low_high_graph.pkl"
STATIC_FILE="/leonardo_work/ICT26_ESP_0/wtang/CORDEXML-GRAPHS/SA_domain_attention/Emulator_hist_future/pr/train/orog.npy"
LOW_INPUT_FILE="/leonardo_work/ICT26_ESP_0/wtang/CORDEXML-GRAPHS/SA_domain_attention/Emulator_hist_future/pr/train/low_input.npy"
TIME_INDEX_FILE="/leonardo_work/ICT26_ESP_0/wtang/CORDEXML-GRAPHS/SA_domain_attention/Emulator_hist_future/pr/train/time_index.npy"
LR_NORM_FILE="/leonardo_work/ICT26_ESP_0/wtang/CORDEXML-BENCHMARK/train/SA_domain/diffusion/Emulator_hist_future/attention_residual_ddpm_recon_wet_loss/lr_norm.npz"
RESIDUAL_NORM_FILE="/leonardo_work/ICT26_ESP_0/wtang/CORDEXML-BENCHMARK/train/SA_domain/diffusion/Emulator_hist_future/attention_residual_ddpm_recon_wet_loss/residual_norm.npz"
CHECKPOINT="/leonardo_work/ICT26_ESP_0/wtang/CORDEXML-BENCHMARK/train/SA_domain/diffusion/Emulator_hist_future/attention_residual_ddpm_recon_wet_loss/best_ema_model.pt"

OUTPUT_PATH="/leonardo_work/ICT26_ESP_0/wtang/CORDEXML-BENCHMARK/train/SA_domain/diffusion/Emulator_hist_future/prediction/attention_residual_ddpm_recon_wet_loss_2098/"
OUTPUT_FILE="G_SA_pr_attention_residual_ddpm_recon_wet_2098.pkl"
LOG_FILE="log.txt"

TARGET_TYPE="precipitation"
VAR="pr"
EXPERIMENT="Emulator_hist_future"
TEST_YEAR_START=2098
DDPM_TIMESTEPS=1000
BETA_START=0.0001
BETA_END=0.02
UNET_BASE=32
LR_HIDDEN=32
TIME_EMB_DIM=64
N_SAMPLES=1
BATCH_SIZE=16
GRID_H=128
GRID_W=128
COARSE_BLOCK_SIZE=8
COARSE_SCALE_MIN=0.0
COARSE_SCALE_MAX=4.0
APPLY_COARSE_CONSERVATION=true
NOISE_SCALE=1.0
REVERSE_NOISE_SCALE=0.85
SNAPSHOT_INTERVAL=200
SEED=42
YEAR_FILTER=2098
