#!/bin/bash

#------------------#
# SLURM PARAMETERS #
#------------------#
TIME="00:30:00" # format HH:MM:SS
MEM="150G"
JOB_NAME="test_prep"


#--------------------------#
# OTHER GENERAL PARAMETERS #
#--------------------------#
DOMAIN="ALPS"
EXPERIMENT="Emulator_hist_future"
LOG_PATH="/leonardo_work/ICT25_ESP/SHARED/CORDEXML-BENCHMARK/logs/"
ENV_PATH="/leonardo_work/ICT25_ESP/SHARED/GNN4CDenv" # conda env
LOG_FILE="log_$DOMAIN_$EXPERIMENT.txt"
SOURCE_PATH="/leonardo/home/userexternal/$USER/.bashrc" # path to the source .bashrc to use conda within the compute node
MAIN_PATH="/leonardo_work/ICT25_ESP/$USER/GNN4CD" # path to the folder


#-------------------------------#
# CHOOSE PREP PHASES TO PERFORM #
#-------------------------------#
PERFORM_PHASE_1=false
PERFORM_PHASE_2=true

#---------------------------#
# INPUT DATA TO PERSONALIZE #
#---------------------------#
# PHASE 1A
INPUT_PATH_PHASE_1="/leonardo_work/ICT25_ESP/SHARED/CORDEXML-BENCHMARK/${DOMAIN}_domain/train/${EXPERIMENT}/predictors/" # to add the domain
OUTPUT_PATH_PHASE_1="/leonardo_work/ICT25_ESP/SHARED/CORDEXML-GRAPHS/${DOMAIN}_domain/train/${EXPERIMENT}/"
PREFIX_PHASE_1="sliced_"
# PHASE 2
OUTPUT_PATH_PHASE_2=${LOG_PATH}
OUTPUT_FILE_PHASE_2="low_high_graph_${DOMAIN}.pkl"
#-- 2A (w resolution data)
INPUT_PATH_PHASE_2="/leonardo_work/ICT25_ESP/SHARED/CORDEXML-GRAPHS/${DOMAIN}_domain/train/${EXPERIMENT}/predictors/"	# where the output of phase 1 is stored
#-- 2B (high resolution data)
INPUT_PATH_TARGET="/leonardo_work/ICT25_ESP/SHARED/CORDEXML-BENCHMARK/${DOMAIN}_domain/train/${EXPERIMENT}/target/"
TARGET_FILE="pr_tasmax_CNRM-CM5_1961-1980_2080-2099.nc"
TARGET_MULTIPLIER=1.0

INPUT_PATH_TOPO="/leonardo_work/ICT25_ESP/SHARED/CORDEXML-BENCHMARK/${DOMAIN}_domain/train/${EXPERIMENT}/predictors/"
TOPO_FILE="Static_fields.nc" #orography

DOMAIN="ALPS"
EXPERIMENT="Emulator_hist_future"


SUFFIX_PHASE_2=""



LON_GRID_RADIUS_HIGH=0.0625 # for the grid of GRIPHO
LAT_GRID_RADIUS_HIGH=0.05 # for the grid of GRIPHO

## e.g. Friuli-Venezia-Giulia region
LON_MIN=12.75
LON_MAX=14.00
LAT_MIN=45.5
LAT_MAX=46.75
INTERVAL=0.25

#--------------do not change here below------------------

PHASE_2_PYTHON_FILE="preprocessing"
