#!/bin/bash

#------------------#
# SLURM PARAMETERS #
#------------------#
TIME="00:30:00" # format HH:MM:SS
MEM="150G"
JOB_NAME="test_prep"


#--------------------------#
# OTHER GENERAL PARAMETERS #
#--------------------------#
DOMAIN="SA"
#EXPERIMENT="Emulator_hist_future"
EXPERIMENT="ESD_pseudo_reality"

#Change log path accordingly
LOG_PATH="/leonardo_work/ICT25_ESP_0/wtang/CORDEXML-BENCHMARK/logs/${EXPERIMENT}_pr_preprocessed/"
ENV_PATH="/leonardo/pub/userexternal/sdigioia/sdigioia/env/RLenv" # conda env
LOG_FILE="log_pr_$DOMAIN_$EXPERIMENT.txt"
SOURCE_PATH="/leonardo/home/userexternal/$USER/Conda_init.txt"
MAIN_PATH="$HOME/benchmarks/GNN4CD-CORDEXML-Benchmark-new/"
#-------------------------------#
# CHOOSE PREP PHASES TO PERFORM #
#-------------------------------#
PERFORM_PHASE_1=false
PERFORM_PHASE_2=true

#---------------------------#
# INPUT DATA TO PERSONALIZE #
#---------------------------#
# PHASE 1A
INPUT_PATH_PHASE_1="/leonardo_work/ICT25_ESP_0/wtang/CORDEXML-BENCHMARK/${DOMAIN}_domain/train/${EXPERIMENT}/predictors/" # to add the domain
OUTPUT_PATH_PHASE_1="/leonardo_work/ICT25_ESP_0/wtang/CORDEXML-GRAPHS/${DOMAIN}_domain/train/${EXPERIMENT}/"
PREFIX_PHASE_1="sliced_"
# PHASE 2
OUTPUT_PATH_PHASE_2=${LOG_PATH}
OUTPUT_FILE_PHASE_2="low_high_graph_${DOMAIN}.pkl"
#-- 2A (w resolution data)
#INPUT_PATH_PHASE_2="/leonardo_work/ICT25_ESP_0/wtang/CORDEXML-GRAPHS/${DOMAIN}_domain/train/${EXPERIMENT}/predictors/"	# where the output of phase 1 is stored
#-- 2B (high resolution data)
INPUT_PATH_TARGET="/leonardo_work/ICT25_ESP_0/wtang/CORDEXML-BENCHMARK/${DOMAIN}_domain/train/${EXPERIMENT}/target/"
#TARGET_FILE="pr_tasmax_CNRM-CM5_1961-1980_2080-2099.nc" #For ALPS
#TARGET_FILE="pr_tasmax_ACCESS-CM2_1961-1980_2080-2099.nc" #For SA Emulator_hist_future
TARGET_FILE="pr_tasmax_ACCESS-CM2_1961-1980.nc" #For SA ESD_pseudo_realit

TARGET_MULTIPLIER=1.0

INPUT_PATH_TOPO="/leonardo_work/ICT25_ESP_0/wtang/CORDEXML-BENCHMARK/${DOMAIN}_domain/train/${EXPERIMENT}/predictors/"
TOPO_FILE="Static_fields.nc" #orography

DOMAIN="SA"
EXPERIMENT="ESD_pseudo_reality"
PREDICTORS_TYPE="era5"

SUFFIX_PHASE_2=""



LON_GRID_RADIUS_HIGH=0.155 # for the grid of GRIPHO
LAT_GRID_RADIUS_HIGH=0.155 # for the grid of GRIPHO

## e.g. SA
LON_MIN=20.50
LON_MAX=33.20
LAT_MIN=-34.70
LAT_MAX=-22.00
INTERVAL=0.25

#--------------do not change here below------------------

PHASE_2_PYTHON_FILE="preprocessing"
