#!/bin/bash

MAIN_PATH="$HOME/benchmarks/Experiments_GNN_diffusion_ddpm_recon_wet_loss"
REPORT_OUTPUT_PATH="/leonardo_work/ICT26_ESP_0/wtang/CORDEXML-BENCHMARK/train/ALPS_domain/diffusion/ESD_pseudo_reality/test/reports/attention_CNRM_CM5/"
REPORT_NAME="attention_CNRM_CM5_pr_ALPS_ESD_extremes"

HISTORICAL_FILE="/leonardo_work/ICT26_ESP_0/wtang/CORDEXML-BENCHMARK/train/ALPS_domain/diffusion/ESD_pseudo_reality/test/attention/historical/perfect/CNRM_CM5_pr_attention.pkl"
MID_CENTURY_FILE="/leonardo_work/ICT26_ESP_0/wtang/CORDEXML-BENCHMARK/train/ALPS_domain/diffusion/ESD_pseudo_reality/test/attention/mid_century/perfect/CNRM_CM5_pr_attention.pkl"
END_CENTURY_FILE="/leonardo_work/ICT26_ESP_0/wtang/CORDEXML-BENCHMARK/train/ALPS_domain/diffusion/ESD_pseudo_reality/test/attention/end_century/perfect/CNRM_CM5_pr_attention.pkl"

FIELD_NAME="pr_gnn4cd"
DAILY_DATE="1992-08-28"
GRID_H=128
GRID_W=128
DAILY_VMAX=75
RX1DAY_VMAX=105
DELTA_MID_VMAX=25
DELTA_END_VMAX=45
