#!/bin/bash

MAIN_PATH="$HOME/benchmarks/Experiments_GNN_diffusion_ddpm_recon_wet_loss"
REPORT_OUTPUT_PATH="/leonardo_work/ICT26_ESP_0/wtang/CORDEXML-BENCHMARK/test/reports/old_gnn/ALPS_domain/ESD_pseudo_reality/CNRM_CM5/"
REPORT_NAME="old_gnn_CNRM_CM5_pr_ALPS_ESD_extremes"

HISTORICAL_FILE="/leonardo_work/ICT26_ESP/SHARED/CORDEX-predictions/ALPS_domain/ESD_pseudo_reality/historical/perfect/CNRM_CM5_pr_pred.pkl"
MID_CENTURY_FILE="/leonardo_work/ICT26_ESP/SHARED/CORDEX-predictions/ALPS_domain/ESD_pseudo_reality/mid_century/perfect/CNRM_CM5_pr_pred.pkl"
END_CENTURY_FILE="/leonardo_work/ICT26_ESP/SHARED/CORDEX-predictions/ALPS_domain/ESD_pseudo_reality/end_century/perfect/CNRM_CM5_pr_pred.pkl"

FIELD_NAME="pr_gnn4cd"
DAILY_DATE="1992-08-28"
GRID_H=128
GRID_W=128
RX1DAY_VMAX=105
DAILY_VMAX=75
DELTA_MID_VMAX=25
DELTA_END_VMAX=45
