#!/bin/bash

MAIN_PATH="$HOME/benchmarks/Experiments_GNN_diffusion_ddpm_recon_wet_loss"
REPORT_OUTPUT_PATH="/leonardo_work/ICT26_ESP_0/wtang/CORDEXML-BENCHMARK/test/reports/old_gnn/SA_domain/Emulator_hist_future/ACCESS_CM2/"
REPORT_NAME="old_gnn_ACCESS_CM2_pr_SA_Emulator_hist_future_extremes"

HISTORICAL_FILE="/leonardo_work/ICT26_ESP/SHARED/CORDEX-predictions/SA_domain/Emulator_hist_future/historical/perfect/ACCESS_CM2_pr_pred.pkl"
MID_CENTURY_FILE="/leonardo_work/ICT26_ESP/SHARED/CORDEX-predictions/SA_domain/Emulator_hist_future/mid_century/perfect/ACCESS_CM2_pr_pred.pkl"
END_CENTURY_FILE="/leonardo_work/ICT26_ESP/SHARED/CORDEX-predictions/SA_domain/Emulator_hist_future/end_century/perfect/ACCESS_CM2_pr_pred.pkl"

FIELD_NAME="pr_gnn4cd"
DAILY_DATE="1998-11-13"
GRID_H=128
GRID_W=128
RX1DAY_VMAX=150
DAILY_VMAX=175
DELTA_MID_VMAX=40
DELTA_END_VMAX=80
