#!/bin/bash

ACCOUNT="ict26_esp_0"
PARTITION="boost_usr_prod"
QOS=""
MAIL="wtang@ictp.it"
TIME="04:00:00"
MEM="60G"
JOB_NAME="rddpm-test-emul-hist"
N_GPU="1"

SOURCE_PATH="/leonardo/home/userexternal/$USER/Conda_init.txt"
ENV_PATH="/leonardo/pub/userexternal/sdigioia/sdigioia/env/RLenv"
MAIN_PATH="$HOME/benchmarks/Experiments_GNN_diffusion_ddpm_recon_wet_loss"
VALENTINA_PATH="$HOME/benchmarks/Experiments_Valentina"

GNN_PRED_FILE="/leonardo_work/ICT26_ESP_0/wtang/CORDEXML-BENCHMARK/train/SA_domain/diffusion/Emulator_hist_future/test/attention/historical/perfect/ACCESS_CM2_pr_attention.pkl"
GRAPH_FILE="/leonardo_work/ICT26_ESP_0/wtang/CORDEXML-GRAPHS/SA_domain_attention/Emulator_hist_future/pr/train/low_high_graph.pkl"
STATIC_FILE="/leonardo_work/ICT26_ESP_0/wtang/CORDEXML-GRAPHS/SA_domain_attention/Emulator_hist_future/pr/train/orog.npy"
LOW_INPUT_FILE=""
TIME_INDEX_FILE=""
TEST_INPUT_PATH_P="/leonardo_work/ICT26_ESP_0/wtang/CORDEXML-BENCHMARK/SA_domain/test/historical/predictors/perfect/"
PREDICTORS_FILE="ACCESS-CM2_1981-2000.nc"
INPUT_GRAPH_PATH="/leonardo_work/ICT26_ESP_0/wtang/CORDEXML-GRAPHS/SA_domain_attention/Emulator_hist_future/pr/train/"
LR_NORM_FILE="/leonardo_work/ICT26_ESP_0/wtang/CORDEXML-BENCHMARK/train/SA_domain/diffusion/Emulator_hist_future/attention_residual_ddpm_recon_wet_loss/lr_norm.npz"
RESIDUAL_NORM_FILE="/leonardo_work/ICT26_ESP_0/wtang/CORDEXML-BENCHMARK/train/SA_domain/diffusion/Emulator_hist_future/attention_residual_ddpm_recon_wet_loss/residual_norm.npz"
CHECKPOINT="/leonardo_work/ICT26_ESP_0/wtang/CORDEXML-BENCHMARK/train/SA_domain/diffusion/Emulator_hist_future/attention_residual_ddpm_recon_wet_loss/checkpoint_ema_199.pt"

OUTPUT_PATH="/leonardo_work/ICT26_ESP_0/wtang/CORDEXML-BENCHMARK/train/SA_domain/diffusion/Emulator_hist_future/test/ddpm_recon_wet_loss/historical/perfect/"
OUTPUT_FILE="ACCESS_CM2_pr_attention_ddpm_recon_wet.pkl"
LOG_FILE="log.txt"

TARGET_TYPE="precipitation"
VAR="pr"
EXPERIMENT="Emulator_hist_future"
TEST_YEAR_START=1981
DDPM_TIMESTEPS=1000
BETA_START=0.0001
BETA_END=0.02
UNET_BASE=32
LR_HIDDEN=32
TIME_EMB_DIM=64
N_SAMPLES=1
BATCH_SIZE=16
GRID_H=128
GRID_W=128
COARSE_BLOCK_SIZE=8
COARSE_SCALE_MIN=0.0
COARSE_SCALE_MAX=4.0
APPLY_COARSE_CONSERVATION=true
NOISE_SCALE=1.0
REVERSE_NOISE_SCALE=0.8
RESIDUAL_SCALE=1.0
SNAPSHOT_INTERVAL=0
SEED=42
YEAR_FILTER=0
MAKE_REPORT=false
