#!/bin/bash

# SLURM
ACCOUNT="ict26_esp_0"
PARTITION="boost_usr_prod"
QOS=""
TIME="10:00:00"
MEM="150G"
JOB_NAME="att-pr-SA-ESD"
N_GPU="1"
MAIL="wtang@ictp.it"

# Paths
SOURCE_PATH="/leonardo/home/userexternal/$USER/Conda_init.txt"
ENV_PATH="/leonardo/pub/userexternal/sdigioia/sdigioia/env/RLenv"
MAIN_PATH="$HOME/benchmarks/Experiments_Attention"
ACCELERATE_CONFIG_PATH="/leonardo/home/userexternal/$USER/.cache/huggingface/accelerate/default_config.yaml"
LOG_PATH="/leonardo_work/ICT26_ESP_0/wtang/CORDEXML-BENCHMARK/train/SA_domain/ESD_pseudo_reality/attention_pr_SA_CosAnnLR_ALPHA01_BETA005_LR0008_bin25/"
OUTPUT_PATH="${LOG_PATH}"
INPUT_PATH="/leonardo_work/ICT26_ESP_0/wtang/CORDEXML-GRAPHS/SA_domain_attention/ESD_pseudo_reality/pr/train/"
LOG_FILE="log.txt"

# Files
LOW_INPUT_FILE="low_input.npy"
OROG_FILE="orog.npy"
MASK_SEALAND_FILE="mask_sealand.npy"
COORDS_IJ_FILE="coords_ij.npy"
TARGET_FILE="target.npy"
METADATA_FILE="low_input_metadata.json"
GRAPH_FILE="low_high_graph.pkl"

# Model/data
SEED=100
MODEL_NAME="GNN4CD_AxialAttention_CrossEdgeFeat_Model"
TARGET_TYPE="precipitation"
DATASET_NAME="Dataset_Graph"
COLLATE_NAME="custom_collate_fn_graph"
HISTORY_LENGTH=2
PREDICTAND_TRANSFORM_MODE="log1p"
PREDICTOR_LOW_TRANSFORM_MODE="zscore_low_var"
PREDICTOR_HIGH_TRANSFORM_MODE="zscore_high_independent"

# Training
EPOCHS=200
BATCH_SIZE=32
LOSS_NAME="MSE_QMSE_PSD_Loss"
LR=0.0008
LR_SCHEDULER="CosineAnnealingLR"
LR_ETA_MIN=1e-6
WEIGHT_DECAY=0.0
ALPHA=0.01
BETA=0.005
BINMIN=0.0
BINMAX=1000
BINWIDTH=0.25
BINSCALE="log"

# Train/validation period
TRAIN_YEAR_START=1961
TRAIN_MONTH_START=1
TRAIN_DAY_START=3
TRAIN_YEAR_END=1979
TRAIN_MONTH_END=12
TRAIN_DAY_END=29
VALIDATION_YEAR=1980
TRAIN_YEARS=""
VAL_YEARS=""

# Logging/validation plots
WANDB_PROJECT_NAME="Attention_pr_SA"
WANDB_API_KEY="d2f9b711020f881fdb31595fe60225e8835b104e"
WANDB_USERNAME="tangwenchang0210"
VAL_PLOT_FREQUENCY=50
VAL_PLOT_CONFIG="${MAIN_PATH}/config_templates/plot/CORDEXML_plot_params_SA.json"

# Flags
USE_ACCELERATE=true
CTD_TRAINING=false
MAKE_VAL_PLOTS=true
CHECKPOINT_CTD=""

if [ ${USE_ACCELERATE} = true ] ; then USE_ACCELERATE="--use_accelerate"; else USE_ACCELERATE="--no-use_accelerate"; fi
if [ ${CTD_TRAINING} = true ] ; then CTD_TRAINING="--ctd_training"; else CTD_TRAINING="--no-ctd_training"; fi
if [ ${MAKE_VAL_PLOTS} = true ] ; then MAKE_VAL_PLOTS="--make_val_plots"; else MAKE_VAL_PLOTS="--no-make_val_plots"; fi
