#!/bin/bash

#------------------#
# SLURM PARAMETERS #
#------------------#
TIME="00:50:00" # format HH:MM:SS
MEM="150G"
JOB_NAME="train_Rall"
LOG_PATH="examples/train/Rall/"
N_GPU=4


#------------------#
# TRAIN PARAMETERS #
#------------------#
SEED=62
#change to P_GNN4CD_CORDEX_model or T_GNN4CD_CORDEX_model
MODEL_NAME="P_GNN4CD_model"
MODEL_TYPE="Rall" # either R, C or Rall
SEQ_L=2

EXPERIMENT="ESD_pseudo_reality"

EPOCHS=50
BATCH_SIZE=32
LR_STEP_SIZE=10
LR=0.001
WEIGHT_DECAY=0.001
LR_SCHEDULER="CosineAnnealingLR"
LOSS_FN="quantized_loss"
ALPHA=0.010

#------------------#
# WANDB PARAMETERS #
#------------------#
WANDB_API_KEY="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"
WANDB_USERNAME="eirene1991"
WANDB_TEAM="climate-dl"
WANDB_PROJECT_NAME="CORDEX-ML"

#--------------------------------------------#
# PATHS (conda env, main, accelerate config) #
#--------------------------------------------#
SOURCE_PATH="/leonardo/home/userexternal/$USER/.bashrc"

ENV_PATH="/leonardo/pub/userexternal/sdigioia/sdigioia/env/RLenv" # conda env
SOURCE_PATH="/leonardo/home/userexternal/$USER/.bashrc"
ACCELERATE_CONFIG_PATH="/leonardo/home/userexternal/$USER/.cache/huggingface/accelerate/default_config.yaml"
MAIN_PATH="/leonardo_work/ICT25_ESP/$USER/CORDEX-ML/GNN4CD-CORDEXML/" # path to the folder

#-------------------------------#
# INPUT/OUTPUT FILES PARAMETERS #
#-------------------------------#

#TODO: change data path
DOMAIN="ALPS"

EXPERIMENT="ESD_pseudo_reality"
#EXPERIMENT="Emulator_hist_future"

#pressure levels
N_LEVELS=3

# PREPROCESSING PHASE 
INPUT_PATH="/leonardo_work/ICT25_ESP/$USER/CORDEX-ML/CORDEX-graphs/${DOMAIN}_domain/${EXPERIMENT}/"
OUTPUT_PATH="/leonardo_work/ICT25_ESP/$USER/CORDEX-ML/Emulator_output/${DOMAIN}_domain/${EXPERIMENT}/wdecay5/"
LOG_PATH=${OUTPUT_PATH}
LOG_FILE="log_$DOMAIN_$EXPERIMENT.txt"
TARGET_FILE="target.pkl"
GRAPH_FILE="low_high_graph.pkl"
OUT_CHECKPOINT_FILE="checkpoint.pth"
DATASET_NAME="Dataset_Graph"
COLLATE_NAME="custom_collate_fn_graph"


#----------------------------------------#
#             TRAINING PERIOD            #
#----------------------------------------#

#here we specify only starting day/month and we specify the years in the train_Rall.py scripts

TRAIN_MONTH_START=1
TRAIN_DAY_START=1
TRAIN_MONTH_END=11
TRAIN_DAY_END=30


#-----------------#
# BOOLEAN OPTIONS #
#-----------------#
USE_ACCELERATE=true
MAKE_VAL_PLOTS=true

#--------------do not change here below------------------

if [ ${USE_ACCELERATE} = true ] ; then
	USE_ACCELERATE="--use_accelerate"
else
	USE_ACCELERATE="--no-use_accelerate"
fi

if [ ${MAKE_VAL_PLOTS} = true ] ; then
	MAKE_VAL_PLOTS="--make_val_plots"
else
	MAKE_VAL_PLOTS="--no-make_val_plots"
fi
