#!/bin/bash

# SLURM
ACCOUNT="ict26_esp_0"
PARTITION="boost_usr_prod"
QOS=""
MAIL="wtang@ictp.it"
TIME="20:00:00"
MEM="150G"
JOB_NAME="att-pr-SA-Emul"
N_GPU="1"

# Paths
SOURCE_PATH="/leonardo/home/userexternal/$USER/Conda_init.txt"
ENV_PATH="/leonardo/pub/userexternal/sdigioia/sdigioia/env/RLenv"
MAIN_PATH="$HOME/benchmarks/Experiments_Attention"
ACCELERATE_CONFIG_PATH="/leonardo/home/userexternal/$USER/.cache/huggingface/accelerate/default_config.yaml"
LOG_PATH="/leonardo_work/ICT26_ESP_0/wtang/CORDEXML-BENCHMARK/train/SA_domain/Emulator_hist_future/attention_pr_SA_Emulator_CosAnnLR_ALPHA01_BETA005_LR0008_bin25_1650/"
OUTPUT_PATH="${LOG_PATH}"
INPUT_PATH="/leonardo_work/ICT26_ESP_0/wtang/CORDEXML-GRAPHS/SA_domain_attention/Emulator_hist_future/pr/train/"
LOG_FILE="log.txt"

# Files
LOW_INPUT_FILE="low_input.npy"
OROG_FILE="orog.npy"
MASK_SEALAND_FILE="mask_sealand.npy"
COORDS_IJ_FILE="coords_ij.npy"
TARGET_FILE="target.npy"
METADATA_FILE="low_input_metadata.json"
GRAPH_FILE="low_high_graph.pkl"

# Model/data
SEED=100
MODEL_NAME="GNN4CD_AxialAttention_CrossEdgeFeat_Model"
TARGET_TYPE="precipitation"
DATASET_NAME="Dataset_Graph"
COLLATE_NAME="custom_collate_fn_graph"
HISTORY_LENGTH=2
PREDICTAND_TRANSFORM_MODE="log1p"
PREDICTOR_LOW_TRANSFORM_MODE="zscore_low_var"
PREDICTOR_HIGH_TRANSFORM_MODE="zscore_high_independent"

# Training
EPOCHS=200
BATCH_SIZE=32
LOSS_NAME="MSE_QMSE_PSD_Loss"
LR=0.0008
LR_SCHEDULER="CosineAnnealingLR"
LR_ETA_MIN=1e-6
WEIGHT_DECAY=0.0
ALPHA=0.01
BETA=0.005
BINMIN=0.0
BINMAX=1650
BINWIDTH=0.25
BINSCALE="log"

# Explicit train/validation years for Emulator_hist_future.
TRAIN_YEAR_START=""
TRAIN_MONTH_START=""
TRAIN_DAY_START=""
TRAIN_YEAR_END=""
TRAIN_MONTH_END=""
TRAIN_DAY_END=""
VALIDATION_YEAR=""
TRAIN_YEARS="1961 1962 1963 1964 1965 1966 1967 1968 1969 1970 1971 1972 1973 1974 1975 1976 1977 1978 1979 1980 2080 2081 2082 2083 2084 2085 2086 2087 2088 2089 2090 2091 2092 2093 2094 2095 2096 2097"
VAL_YEARS="2098 2099"

# Logging/validation plots
WANDB_PROJECT_NAME="Attention_pr_SA_Emulator"
WANDB_API_KEY="d2f9b711020f881fdb31595fe60225e8835b104e"
WANDB_USERNAME="tangwenchang0210"
VAL_PLOT_FREQUENCY=50
VAL_PLOT_CONFIG="${MAIN_PATH}/config_templates/plot/CORDEXML_plot_params_SA.json"

# Flags
USE_ACCELERATE=true
CTD_TRAINING=false
MAKE_VAL_PLOTS=true
CHECKPOINT_CTD=""

if [ ${USE_ACCELERATE} = true ] ; then USE_ACCELERATE="--use_accelerate"; else USE_ACCELERATE="--no-use_accelerate"; fi
if [ ${CTD_TRAINING} = true ] ; then CTD_TRAINING="--ctd_training"; else CTD_TRAINING="--no-ctd_training"; fi
if [ ${MAKE_VAL_PLOTS} = true ] ; then MAKE_VAL_PLOTS="--make_val_plots"; else MAKE_VAL_PLOTS="--no-make_val_plots"; fi
