#!/bin/bash

# Temperature residual DDPM. Wet/dry auxiliary loss is disabled for tasmax.
ACCOUNT=ict26_esp_0
PARTITION=boost_usr_prod
QOS=
MAIL=wtang@ictp.it
TIME=6:00:00
MEM=120G
JOB_NAME=att-rddpm-tasmax-emul
N_GPU=1

SOURCE_PATH=/leonardo/home/userexternal/wtang001/Conda_init.txt
ENV_PATH=/leonardo/pub/userexternal/sdigioia/sdigioia/env/RLenv
MAIN_PATH=/leonardo/home/userexternal/wtang001/benchmarks/Experiments_GNN_diffusion_ddpm_recon_wet_loss

GNN_PRED_FILE=/leonardo_work/ICT26_ESP_0/wtang/CORDEXML-BENCHMARK/train/SA_domain/Emulator_hist_future/predictions/attention/attention_tasmax_SA_Emulator_StepLR50_gamma07_WD00_e300_train1961_1980_2080_2099/G_SA_attention_tasmax_train_1961_1980_2080_2099.pkl
TARGET_FILE=/leonardo_work/ICT26_ESP_0/wtang/CORDEXML-GRAPHS/SA_domain_attention/Emulator_hist_future/tasmax/train/target.npy
TIME_INDEX_FILE=/leonardo_work/ICT26_ESP_0/wtang/CORDEXML-GRAPHS/SA_domain_attention/Emulator_hist_future/tasmax/train/time_index.npy
LOW_INPUT_FILE=/leonardo_work/ICT26_ESP_0/wtang/CORDEXML-GRAPHS/SA_domain_attention/Emulator_hist_future/tasmax/train/low_input.npy
GRAPH_FILE=/leonardo_work/ICT26_ESP_0/wtang/CORDEXML-GRAPHS/SA_domain_attention/Emulator_hist_future/tasmax/train/low_high_graph.pkl
STATIC_FILE=/leonardo_work/ICT26_ESP_0/wtang/CORDEXML-GRAPHS/SA_domain_attention/Emulator_hist_future/tasmax/train/orog.npy

OUTPUT_PATH=/leonardo_work/ICT26_ESP_0/wtang/CORDEXML-BENCHMARK/train/SA_domain/diffusion/Emulator_hist_future/attention_residual_ddpm_tasmax_recon_loss/
LOG_FILE=log.txt
TARGET_TYPE=temperature
TRAIN_YEARS=1961_1962_1963_1964_1965_1966_1967_1968_1969_1970_1971_1972_1973_1974_1975_1976_1977_1978_1979_1980_2080_2081_2082_2083_2084_2085_2086_2087_2088_2089_2090_2091_2092_2093_2094_2095_2096_2097
VAL_YEARS=2098_2099
EPOCHS=200
BATCH_SIZE=32
LR=0.00015
WEIGHT_DECAY=0.0
LAMBDA_RECON=0.02
LAMBDA_WET=0.0
WET_THRESHOLD=0.0
CHECKPOINT_INTERVAL=10
VAL_SEED=12345
VAL_REPEATS=1
DDPM_TIMESTEPS=1000
UNET_BASE=32
LR_HIDDEN=32
TIME_EMB_DIM=64
BETA_START=0.0001
BETA_END=0.02
GRID_H=128
GRID_W=128
AUX_RESIDUAL_MODEL_CLIP=8.0
AUX_LOG_CLIP=8.0
NORMALIZE_RESIDUAL_FLAG=--normalize_residual
USE_EMA_FLAG=--use_ema
EMA_DECAY=0.999
SEED=42
WANDB_PROJECT_NAME=DDPM_tasmax_SA_Emulator
WANDB_API_KEY=d2f9b711020f881fdb31595fe60225e8835b104e
WANDB_USERNAME=tangwenchang0210
WANDB_MODE=offline

