#!/bin/bash

#------------------#
# SLURM PARAMETERS #
#------------------#
TIME="15:00:00"
MEM="150G"
JOB_NAME="gnll-SA-Emu-C"
MAIL="wtang@ictp.it"
LOG_PATH="/leonardo_work/ICT26_ESP_0/wtang/CORDEXML-BENCHMARK/train/SA_domain/Emulator_hist_future/0416_tasmax_SA_Emulator_StepLR50_gamma07_WD00/"
N_GPU="1"
SEED=100
MODEL_NAME="GNN4CD_model_mod1_GaussianNLL"
MODEL_TYPE="Rall"
TARGET_TYPE="temperature"
LR_SCHEDULER="StepLR"
RUN_TYPE="CORDEXML"

#--------------------------------------------#
# PATHS (conda env, main, accelerate config) #
#--------------------------------------------#
SOURCE_PATH="/leonardo/home/userexternal/$USER/Conda_init.txt"
ENV_PATH="/leonardo/pub/userexternal/sdigioia/sdigioia/env/RLenv"
MAIN_PATH="$HOME/benchmarks/Experiments_Valentina"
ACCELERATE_CONFIG_PATH="/leonardo/home/userexternal/$USER/.cache/huggingface/accelerate/default_config.yaml"

#-------------------------------#
# INPUT/OUTPUT FILES PARAMETERS #
#-------------------------------#
INPUT_PATH="/leonardo_work/ICT26_ESP_0/wtang/CORDEXML-GRAPHS/SA_domain_0403/Emulator_hist_future/tasmax/train/"
OUTPUT_PATH=${LOG_PATH}
LOG_FILE="log.txt"
LOW_INPUT_FILE="low_input.npy"
OROG_FILE="orog.npy"
MASK_SEALAND_FILE="mask_sealand.npy"
COORDS_IJ_FILE="coords_ij.npy"
TARGET_FILE="target.npy"
METADATA_FILE="low_input_metadata.json"
GRAPH_FILE="low_high_graph.pkl"
DATASET_NAME="Dataset_Graph"
COLLATE_NAME="custom_collate_fn_graph"

#---------------------#
# TRAINING PARAMETERS #
#---------------------#
EPOCHS=300
BATCH_SIZE=64
LR_STEP_SIZE=50
LR_GAMMA=0.7
LR=0.001
WEIGHT_DECAY=0.0
LOSS_FN="GaussianNLLLoss"
ALPHA=0.0
BETA=0.0
BALANCE=""
WANDB_PROJECT_NAME="CORDEXML_tasmax_SA_Emulator"

#----------------------------------------#
#  TRAINING PERIOD (non-contiguous)      #
#  1961-1980 + 2080-2097, val = 2098-2099#
#----------------------------------------#
TRAIN_YEAR_START=1961
TRAIN_MONTH_START=1
TRAIN_DAY_START=3
TRAIN_YEAR_END=2099
TRAIN_MONTH_END=12
TRAIN_DAY_END=29
VALIDATION_YEAR=2098

FIRST_YEAR=0
LAST_YEAR=0
N_VAL_YEARS=0

# Explicit list of training years (all of 1961-1980 and 2080-2097, excluding val years 2098-2099)
TRAIN_YEARS="1961 1962 1963 1964 1965 1966 1967 1968 1969 1970 1971 1972 1973 1974 1975 1976 1977 1978 1979 1980 2080 2081 2082 2083 2084 2085 2086 2087 2088 2089 2090 2091 2092 2093 2094 2095 2096 2097"
VAL_YEARS="2098 2099"

#-----------------#
# BOOLEAN OPTIONS #
#-----------------#
CTD_TRAINING=false
FINE_TUNING=true
USE_ACCELERATE=true
MAKE_VAL_PLOTS=true
CHECKPOINT_CTD=""

#--------------do not change here below------------------

if [ ${USE_ACCELERATE} = true ] ; then
	USE_ACCELERATE="--use_accelerate"
else
	USE_ACCELERATE="--no-use_accelerate"
fi

if [ ${CTD_TRAINING} = true ] ; then
	CTD_TRAINING="--ctd_training"
else
	CTD_TRAINING="--no-ctd_training"
fi

if [ ${FINE_TUNING} = true ] ; then
	FINE_TUNING="--fine_tuning"
else
	FINE_TUNING="--no-fine_tuning"
fi

if [ ${MAKE_VAL_PLOTS} = true ] ; then
	MAKE_VAL_PLOTS="--make_val_plots"
else
	MAKE_VAL_PLOTS="--no-make_val_plots"
fi
