#!/bin/bash

#------------------#
# SLURM PARAMETERS #
#------------------#
TIME="00:30:00" # format HH:MM:SS
MEM="150G"
JOB_NAME="train_Rall"
N_GPU=4

#------------------#
# TEST PARAMETERS #
#------------------#
SEED=62
#change to P_GNN4CD_CORDEX_model or T_GNN4CD_CORDEX_model
MODEL_NAME="P_GNN4CD_model"  #
MODEL_TYPE="Rall" # either R, C or Rall
SEQ_L=2
VAR_TYPE=
STATS_MODE="var"


LR_SCHEDULER="StepLR"


EPOCH=20
BATCH_SIZE=32
LR_STEP_SIZE=25
LR=0.0001
WEIGHT_DECAY=0.0
LOSS_FN="quantized_loss"
ALPHA=0.005
#------------------#
# WANDB PARAMETERS #
#------------------#
WANDB_API_KEY="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"
WANDB_USERNAME="eirene1991"
WANDB_TEAM="climate-dl"
WANDB_PROJECT_NAME="CORDEX-ML"

#--------------------------------------------#
# PATHS (conda env, main, accelerate config) #
#--------------------------------------------#

SOURCE_PATH="/leonardo/home/userexternal/$USER/.bashrc"

ENV_PATH="/leonardo/pub/userexternal/sdigioia/sdigioia/env/RLenv" # conda env
SOURCE_PATH="/leonardo/home/userexternal/$USER/.bashrc"
ACCELERATE_CONFIG_PATH="/leonardo/home/userexternal/$USER/.cache/huggingface/accelerate/default_config.yaml"
MAIN_PATH="/leonardo_work/ICT25_ESP/$USER/CORDEX-ML/GNN4CD-CORDEXML/" # path to the folder

#-------------------------------#
# INPUT/OUTPUT FILES PARAMETERS #
#-------------------------------#

DOMAIN="ALPS"

EXPERIMENT="ESD_pseudo_reality"
#EXPERIMENT="Emulator_hist_future"

#pressure levels
N_LEVELS=3

# PREPROCESSING PHASE 
INPUT_PATH="/leonardo_work/ICT25_ESP/$USER/CORDEX-ML/CORDEX-graphs/${DOMAIN}_domain/${EXPERIMENT}/"
OUTPUT_PATH="/leonardo_work/ICT25_ESP/$USER/CORDEX-ML/Emulator_output/${DOMAIN}_domain/${EXPERIMENT}/predictions/mse_20/"
LOG_PATH=${OUTPUT_PATH}
TRAIN_PATH="/leonardo_work/ICT25_ESP/$USER/CORDEX-ML/Emulator_output/${DOMAIN}_domain/${EXPERIMENT}/mse/"
CHECKPOINT_REG="checkpoint_${EPOCH}"

LOG_FILE="log_validation_output.txt"
OUTPUT_FILE="validation_precipitation_epoch_20.pkl"
OUTPUT_FILE_SEASONS="validation_seasonal_precipitation_epoch_20.pkl"
TARGET_FILE="target.pkl"
TARGET_TYPE="precipitation"
GRAPH_FILE="low_high_graph.pkl"

CHECKPOINT_FILE="checkpoint.pth"
TEST_IDXS_FILE=""
DATASET_NAME="Dataset_Graph"
COLLATE_NAME="custom_collate_fn_graph"


#----------------------------------------#
#             INFERENCE PERIOD            #
#----------------------------------------#

#change inference period to CORDEX
VALIDATION_YEAR=1975
TEST_MONTH_START=1
TEST_DAY_START=1
TEST_MONTH_END=12
TEST_DAY_END=31


#-----------------#
# BOOLEAN OPTIONS #
#-----------------#
USE_ACCELERATE=true


#--------------do not change here below------------------

if [ ${USE_ACCELERATE} = true ] ; then
	USE_ACCELERATE="--use_accelerate"
else
	USE_ACCELERATE="--no-use_accelerate"
fi
