#!/bin/bash

#------------------#
# SLURM PARAMETERS #
#------------------#
ACCOUNT="ict26_esp_0"
PARTITION="boost_usr_prod"
QOS="boost_qos_dbg"
TIME="00:30:00"
MEM="250G"
JOB_NAME="prep-ALPS"
LOG_PATH=""

DATASET_NAME="CORDEXML"
PARAMS="q,t,u,v,z"
LEVELS="850,700,500"
TARGET_VARIABLES="pr,tasmax"
TARGET_MULTIPLIERS="1.0,1.0"

#--------------------------#
# OTHER GENERAL PARAMETERS #
#--------------------------#
ENV_PATH="/leonardo/pub/userexternal/sdigioia/sdigioia/env/RLenv"
LOG_FILE="log.txt"
SOURCE_PATH="./conda_init"
MAIN_PATH=""

#-------------------#
# INPUT/OUTPUT DATA #
#-------------------#
OUTPUT_PATH=${LOG_PATH}
OUTPUT_FILE="low_high_graph_edgeattr.pkl"
INPUT_PATH_PREDICTORS="/leonardo_work/ICT26_ESP/sdigioia/CORDEX-ML/CORDEX-domains/ALPS_domain/train/ESD_pseudo_reality/predictors/"
PREDICTORS_FILE="CNRM-CM5_1961-1980.nc"
INPUT_PATH_TARGET="/leonardo_work/ICT26_ESP/sdigioia/CORDEX-ML/CORDEX-domains/ALPS_domain/train/ESD_pseudo_reality/target/"
TARGET_FILE="pr_tasmax_CNRM-CM5_1961-1980.nc"

INPUT_PATH_TOPO="/leonardo_work/ICT26_ESP/SHARED/TOPO/"
TOPO_FILE="Static_fields_fixed_ALPS.nc"
INPUT_PATH_MASK_SEALAND="/leonardo_work/ICT26_ESP/SHARED/TOPO/"
MASK_SEALAND_FILE="mask_sealand_CORDEXML_ALPS.nc"

LON_GRID_RADIUS_HIGH=0.25
LAT_GRID_RADIUS_HIGH=0.15
K_LOW2HIGH=9
