#!/bin/bash

#------------------#
# SLURM PARAMETERS #
#------------------#
ACCOUNT="ict26_esp_0"
PARTITION="boost_qos_dbg"
QOS="boost_qos_dbg"
TIME="00:30:00"
MEM="250G"
JOB_NAME="pr"
MAIL=""

DOMAIN="ALPS"
LOG_PATH=""
TARGET_TYPE="precipitation"
DATASET_NAME="CORDEXML"
PARAMS="q,t,u,v,z"
LEVELS="500,700,850"

#--------------------------#
# OTHER GENERAL PARAMETERS #
#--------------------------#
ENV_PATH="/leonardo/home/userexternal/vblasone/.conda/envs/GNN4CDenv"
LOG_FILE="log.txt"
SOURCE_PATH="/leonardo/home/userexternal/vblasone/.bashrc"
MAIN_PATH="/leonardo_work/ICT26_ESP/vblasone/GNN4CD-CORDEXML"

#---------------------------#
# INPUT DATA TO PERSONALIZE #
#---------------------------#
# PHASE 2
OUTPUT_PATH=${LOG_PATH}
OUTPUT_FILE="low_high_graph.pkl"
INPUT_PATH_PREDICTORS="/leonardo_work/ICT26_ESP/sdigioia/CORDEX-ML/CORDEX-domains/${DOMAIN}_domain/train/ESD_pseudo_reality/predictors/"
PREDICTORS_FILE="CNRM-CM5_1961-1980.nc"
INPUT_PATH_TARGET="/leonardo_work/ICT26_ESP/sdigioia/CORDEX-ML/CORDEX-domains/${DOMAIN}_domain/train/ESD_pseudo_reality/target/"
TARGET_FILE="pr_tasmax_CNRM-CM5_1961-1980.nc"
TARGET_MULTIPLIER=1.0

INPUT_PATH_TOPO="/leonardo_work/ICT26_ESP/SHARED/TOPO/"
TOPO_FILE="Static_fields_fixed.nc"
INPUT_PATH_MASK_SEALAND="/leonardo_work/ICT26_ESP/SHARED/TOPO/"
MASK_SEALAND_FILE="mask_sealand_CORDEXML.nc"

LON_GRID_RADIUS_HIGH=0.25
LAT_GRID_RADIUS_HIGH=0.15


